### ISSUE TITLE
WiFi Reconnect only after power cycle

### ISSUE THREAD

**Issue by PhillipJacobsen** [PhillipJacobsen/GetTickerCaptivePortal#4]
It seems like most of the time WiFi will only reconnect to the network after a power cycle and not when the reset button on the board is pressed.  
This could be the same issue discussed here.
https://github.com/esp8266/Arduino/issues/2235

**Comment by PhillipJacobsen** [comment]
Problem occurs with ESP8266 Core v2.4 (ESP8266 Community in Board Manager)
**When I switched to V2.3 the problem appeared to go away.**
The problem also seemed to go away with V2.4rc2
I assume 2.4 is newer then 2.4rc2

**Comment by PhillipJacobsen** [comment]
problem solved

**Comment by sampath1994** [comment]
problem solved with V2.4rc2 , but not with V2.3
